Git hook cleanup

diff --git a/git/hooks/pre-push b/git/hooks/pre-push
--- a/git/hooks/pre-push
+++ b/git/hooks/pre-push
@@ -2,16 +2,27 @@
 protected_branch='master'  
 current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
 
-if [ $protected_branch = $current_branch ]; then  
-    echo -en "\033[31mYou're about to push master, are you sure? [y|n] \033[0m"
-    echo -en "\033[1m"
-    read -n 1 -r < /dev/tty
-    echo -en "\033[0m"
-    echo
-    if echo $REPLY | grep -E '^[Yy]$' > /dev/null; then
-        exit 0 # OK
-    fi
-    exit 1 # Fail
-else
-    exit 0 # OK
+# ignore slingshot
+if [[ `pwd` =~ 'slingshot/data' ]]; then
+    exit 0; # OK 
 fi
+
+# Not master, go go go
+if ! [ $protected_branch = $current_branch ]; then
+    exit 0; # OK
+fi
+
+tput bold && tput setaf 1;
+echo -n "You're about to push master, are you sure? [y|N]"
+tput sgr0;
+
+read -n 1 -r < /dev/tty;
+echo;
+
+# Confirmed, OK to go
+if echo $REPLY | grep -E '^[Yy]$' > /dev/null; then
+    exit 0; # OK
+fi
+
+# Not confirmed, error out
+exit 1; # Fail
